WINDOW_WIDTH = 500
WINDOW_HEIGHT = 500
COLOR_RED = (255,0,0)
COLOR_BLUE = (0,0,255)
COLOR_GREEN = (0,255,0)
COLOR_BLACK = (0,0,0)
COLOR_ORANGE = (255,165,0)
COLOR_WHITE = (255,255,255)
COLOR_PURPLE = (139, 0, 255)
DEATH_MASS = 5
MINIMUM_MASS = 6
MASS_TO_SPAWN_AFTER_START = 6
FOOD_MASS = 1
START_MASS = 5000
START_TEAM_BALL_MASS = 500
START_CLUSTER_RADIUS = 70
TEAM_BLUE=0
TEAM_RED=1

CONTROL_MODE_PLAYER = "player"
CONTROL_MODE_AI_VS_AI = "ai_vs_ai"
CONTROL_MODE = CONTROL_MODE_PLAYER
PLAYER_TEAM = TEAM_BLUE
BALL_VIEW_FACTOR=3
IMPORTANCE_KOEF = 0
WANDER_FACTOR= 1.1
FOOD_DISTANCE_FACTOR=0.04
WALL_DISTANCE_FACTOR = 0.12
WALL_INTENT_PEAK = 8.0
BALL_INTENT_SMOOTH_STEP = 0.18

INTENT_MERGE_EPSILON = 2.0
INTENT_MERGE_CLAMP = 3.0

INTENT_MIN_BASELINE = 0.5
INTENT_DEAD_ZONE = 0.05
INTENT_TOP_BALLS = 50
INTENT_WEIGHT_FOOD = 0.1
FOOD_INTENT_SMOOTH_STEP = 0.01

FOOD_INTENT_FOOD_COUNT_K = 0.05
AI_SPLIT_MIN_FOOD = 4
AI_SPLIT_FOOD_PER = 6
AI_SPLIT_MAX_PER_UPDATE = 1
AI_SPLIT_COOLDOWN = 1.0
COMMAND_GATHER_FACTOR = 3.0
COMMAND_GATHER_INTENT_MULT = 2.5
INTENT_WEIGHT_BALLS = 1
INTENT_WEIGHT_WALL = 10
INTENT_WEIGHT_WANDER = 1
INTENT_WEIGHT_COMMAND = 1
INTENT_LOOK_AHEAD = 50

CELL_SIZE = 6